server:
  port: 10002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
logging:
  level:
    root: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
