server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuliangliang1995/grasswort-config-repo.git
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


